import { PromptState, Preset } from './types';

export const INITIAL_STATE: PromptState = {
  subject: '',
  action: '',
  environment: '',
  shotType: 'Wide Shot',
  angle: 'Eye Level',
  lighting: 'Natural Light',
  mood: 'Cinematic',
  camera: 'Digital Cinema',
  lens: '35mm',
  filmLook: 'None',
  style: 'Photorealistic',
  movieLook: 'None',
  effect: 'None',
};

export const SAMPLE_PRESETS: Preset[] = [
  {
    id: 'p1',
    name: 'Neo-Noir Cyberpunk',
    description: 'High contrast, neon lights, rain-slicked streets, futuristic vibe.',
    coverImage: 'https://picsum.photos/400/225?grayscale',
    data: {
      subject: 'A mysterious hacker with a cybernetic arm',
      action: 'standing in the rain looking at a hologram',
      environment: 'futuristic Tokyo back alley at night',
      shotType: 'Medium Shot',
      angle: 'Low Angle',
      lighting: 'Neon Blue and Pink Volumetric',
      mood: 'Moody, Dystopian',
      camera: 'Sony Venice 2',
      lens: 'Anamorphic 50mm',
      filmLook: 'Kodak Vision3 500T',
      style: 'Photorealistic',
      movieLook: 'Blade Runner 2049',
      effect: 'Chromatic Aberration',
    },
  },
  {
    id: 'p2',
    name: 'Luxury Editorial',
    description: 'Clean, bright, high-fashion aesthetic for premium brands.',
    coverImage: 'https://picsum.photos/400/225?blur',
    data: {
      subject: 'Elegant model wearing haute couture',
      action: 'posing confidently',
      environment: 'Minimalist concrete architectural space',
      shotType: 'Full Body',
      angle: 'Eye Level',
      lighting: 'Soft Box Studio Lighting',
      mood: 'Sophisticated, Expensive',
      camera: 'Hasselblad H6D',
      lens: '85mm Portrait',
      filmLook: 'Fujifilm Pro 400H',
      style: 'Fashion Photography',
      movieLook: 'None',
      effect: 'Bloom Glow',
    },
  },
  {
    id: 'p3',
    name: 'Spaghetti Western',
    description: 'Gritty textures, harsh sun, extreme close-ups.',
    coverImage: 'https://picsum.photos/400/225?sepia',
    data: {
      subject: 'Weathered gunslinger',
      action: 'staring down an opponent',
      environment: 'Dusty desert town at high noon',
      shotType: 'Extreme Close Up (Eyes)',
      angle: 'Dutch Angle',
      lighting: 'Harsh Sunlight',
      mood: 'Tense, Gritty',
      camera: 'Arriflex 35',
      lens: 'Telephoto Zoom',
      filmLook: 'Technicolor',
      style: 'Cinematic',
      movieLook: 'The Good, the Bad and the Ugly',
      effect: 'Film Grain',
    },
  }
];

export const OPTIONS = {
  shotTypes: ['Extreme Wide Shot', 'Wide Shot', 'Medium Shot', 'Close-up', 'Extreme Close-up', 'Cowboy Shot'],
  angles: ['Eye Level', 'Low Angle', 'High Angle', 'Bird\'s Eye View', 'Worm\'s Eye View', 'Dutch Angle'],
  lighting: ['Golden Hour', 'Blue Hour', 'Midday Sun', 'Studio Softbox', 'Rembrandt', 'Neon Volumetric', 'Candlelight', 'Bioluminescent'],
  cameras: ['Sony Venice 2', 'RED Komodo', 'Arri Alexa Mini', 'IMAX 70mm', 'Hasselblad H6D', 'iPhone 15 Pro', 'Vintage Polaroid'],
  lenses: ['14mm Ultra Wide', '24mm Wide', '35mm Street', '50mm Standard', '85mm Portrait', '100mm Macro', 'Anamorphic'],
  filmLooks: ['None', 'Kodak Portra 400', 'Kodak Gold 200', 'Cinestill 800T', 'Ilford HP5 (B&W)', 'Technicolor Process 4'],
  styles: ['Photorealistic', '3D Render (Octane)', 'Anime', 'Oil Painting', 'Watercolor', 'Concept Art', 'Unreal Engine 5'],
  movieLooks: ['None', 'Blade Runner 2049', 'The Grand Budapest Hotel', 'Mad Max: Fury Road', 'The Matrix', 'Dune', 'Cyberpunk 2077'],
  effects: ['None', 'Bloom Glow', 'Chromatic Aberration', 'Vignette', 'Film Grain', 'Lens Flare', 'Motion Blur'],
};